
    package net.scalax.simple.adt
    package instance
    package support

    object AdtFunctionSupport {
      AdtFunctionSupportSelf =>

      val inputHList0: (AdtCoProduct, AdtHList) => AdtCoProduct = (a1: AdtCoProduct, b1: AdtHList) => (a1: AdtCoProduct)

      
      def inputHList1[T1, N1]: (AdtCoProduct.UsePositive[T1, AdtCoProduct], AdtHList.UsePositive[T1 => N1, AdtHList]) => AdtCoProduct.UsePositive[N1, AdtCoProduct] = {
        AdtInstanceFunc.appendSimpleAdt.next[T1, N1, AdtCoProduct, AdtHList, AdtCoProduct](AdtFunctionSupportSelf.inputHList0)
      }
    

      def inputHList2[T1,T2, N1,N2]: (AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]], AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]) => AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T2, N2, AdtCoProduct.UsePositive[T1, AdtCoProduct], AdtHList.UsePositive[T1 => N1, AdtHList], AdtCoProduct.UsePositive[N1, AdtCoProduct]](AdtFunctionSupportSelf.inputHList1[T1,N1])
      }
    

      def inputHList3[T1,T2,T3, N1,N2,N3]: (AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]], AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]) => AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T3, N3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]], AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]], AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]](AdtFunctionSupportSelf.inputHList2[T1,T2,N1,N2])
      }
    

      def inputHList4[T1,T2,T3,T4, N1,N2,N3,N4]: (AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]], AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]) => AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T4, N4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]], AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]], AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]](AdtFunctionSupportSelf.inputHList3[T1,T2,T3,N1,N2,N3])
      }
    

      def inputHList5[T1,T2,T3,T4,T5, N1,N2,N3,N4,N5]: (AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]], AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]) => AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T5, N5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]], AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]], AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]](AdtFunctionSupportSelf.inputHList4[T1,T2,T3,T4,N1,N2,N3,N4])
      }
    

      def inputHList6[T1,T2,T3,T4,T5,T6, N1,N2,N3,N4,N5,N6]: (AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]], AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]) => AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T6, N6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]], AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]], AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]](AdtFunctionSupportSelf.inputHList5[T1,T2,T3,T4,T5,N1,N2,N3,N4,N5])
      }
    

      def inputHList7[T1,T2,T3,T4,T5,T6,T7, N1,N2,N3,N4,N5,N6,N7]: (AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]], AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]) => AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T7, N7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]], AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]], AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]](AdtFunctionSupportSelf.inputHList6[T1,T2,T3,T4,T5,T6,N1,N2,N3,N4,N5,N6])
      }
    

      def inputHList8[T1,T2,T3,T4,T5,T6,T7,T8, N1,N2,N3,N4,N5,N6,N7,N8]: (AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]], AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]) => AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T8, N8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]], AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]], AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]](AdtFunctionSupportSelf.inputHList7[T1,T2,T3,T4,T5,T6,T7,N1,N2,N3,N4,N5,N6,N7])
      }
    

      def inputHList9[T1,T2,T3,T4,T5,T6,T7,T8,T9, N1,N2,N3,N4,N5,N6,N7,N8,N9]: (AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]], AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]) => AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T9, N9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]], AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]], AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]](AdtFunctionSupportSelf.inputHList8[T1,T2,T3,T4,T5,T6,T7,T8,N1,N2,N3,N4,N5,N6,N7,N8])
      }
    

      def inputHList10[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10]: (AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]], AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]) => AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T10, N10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]], AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]], AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]](AdtFunctionSupportSelf.inputHList9[T1,T2,T3,T4,T5,T6,T7,T8,T9,N1,N2,N3,N4,N5,N6,N7,N8,N9])
      }
    

      def inputHList11[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11]: (AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]], AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]) => AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T11, N11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]], AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]], AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]](AdtFunctionSupportSelf.inputHList10[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10])
      }
    

      def inputHList12[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12]: (AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]], AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T12, N12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]], AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]], AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList11[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11])
      }
    

      def inputHList13[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13]: (AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]], AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T13, N13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]], AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]], AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList12[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12])
      }
    

      def inputHList14[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14]: (AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]], AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T14, N14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]], AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]], AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList13[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13])
      }
    

      def inputHList15[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15]: (AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]], AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T15, N15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]], AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList14[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14])
      }
    

      def inputHList16[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16]: (AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]], AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T16, N16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]], AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList15[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15])
      }
    

      def inputHList17[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17]: (AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T17, N17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]], AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList16[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16])
      }
    

      def inputHList18[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18]: (AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T18, N18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList17[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17])
      }
    

      def inputHList19[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19]: (AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T19, N19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList18[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18])
      }
    

      def inputHList20[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19,N20]: (AdtCoProduct.UsePositive[T20, AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T20 => N20, AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N20, AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T20, N20, AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList19[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19])
      }
    

      def inputHList21[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19,N20,N21]: (AdtCoProduct.UsePositive[T21, AdtCoProduct.UsePositive[T20, AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T21 => N21, AdtHList.UsePositive[T20 => N20, AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N21, AdtCoProduct.UsePositive[N20, AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T21, N21, AdtCoProduct.UsePositive[T20, AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T20 => N20, AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N20, AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList20[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19,N20])
      }
    

      def inputHList22[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22, N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19,N20,N21,N22]: (AdtCoProduct.UsePositive[T22, AdtCoProduct.UsePositive[T21, AdtCoProduct.UsePositive[T20, AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T22 => N22, AdtHList.UsePositive[T21 => N21, AdtHList.UsePositive[T20 => N20, AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]]]]]) => AdtCoProduct.UsePositive[N22, AdtCoProduct.UsePositive[N21, AdtCoProduct.UsePositive[N20, AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]]] = {
        AdtInstanceFunc.appendSimpleAdt.next[T22, N22, AdtCoProduct.UsePositive[T21, AdtCoProduct.UsePositive[T20, AdtCoProduct.UsePositive[T19, AdtCoProduct.UsePositive[T18, AdtCoProduct.UsePositive[T17, AdtCoProduct.UsePositive[T16, AdtCoProduct.UsePositive[T15, AdtCoProduct.UsePositive[T14, AdtCoProduct.UsePositive[T13, AdtCoProduct.UsePositive[T12, AdtCoProduct.UsePositive[T11, AdtCoProduct.UsePositive[T10, AdtCoProduct.UsePositive[T9, AdtCoProduct.UsePositive[T8, AdtCoProduct.UsePositive[T7, AdtCoProduct.UsePositive[T6, AdtCoProduct.UsePositive[T5, AdtCoProduct.UsePositive[T4, AdtCoProduct.UsePositive[T3, AdtCoProduct.UsePositive[T2, AdtCoProduct.UsePositive[T1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]], AdtHList.UsePositive[T21 => N21, AdtHList.UsePositive[T20 => N20, AdtHList.UsePositive[T19 => N19, AdtHList.UsePositive[T18 => N18, AdtHList.UsePositive[T17 => N17, AdtHList.UsePositive[T16 => N16, AdtHList.UsePositive[T15 => N15, AdtHList.UsePositive[T14 => N14, AdtHList.UsePositive[T13 => N13, AdtHList.UsePositive[T12 => N12, AdtHList.UsePositive[T11 => N11, AdtHList.UsePositive[T10 => N10, AdtHList.UsePositive[T9 => N9, AdtHList.UsePositive[T8 => N8, AdtHList.UsePositive[T7 => N7, AdtHList.UsePositive[T6 => N6, AdtHList.UsePositive[T5 => N5, AdtHList.UsePositive[T4 => N4, AdtHList.UsePositive[T3 => N3, AdtHList.UsePositive[T2 => N2, AdtHList.UsePositive[T1 => N1, AdtHList]]]]]]]]]]]]]]]]]]]]], AdtCoProduct.UsePositive[N21, AdtCoProduct.UsePositive[N20, AdtCoProduct.UsePositive[N19, AdtCoProduct.UsePositive[N18, AdtCoProduct.UsePositive[N17, AdtCoProduct.UsePositive[N16, AdtCoProduct.UsePositive[N15, AdtCoProduct.UsePositive[N14, AdtCoProduct.UsePositive[N13, AdtCoProduct.UsePositive[N12, AdtCoProduct.UsePositive[N11, AdtCoProduct.UsePositive[N10, AdtCoProduct.UsePositive[N9, AdtCoProduct.UsePositive[N8, AdtCoProduct.UsePositive[N7, AdtCoProduct.UsePositive[N6, AdtCoProduct.UsePositive[N5, AdtCoProduct.UsePositive[N4, AdtCoProduct.UsePositive[N3, AdtCoProduct.UsePositive[N2, AdtCoProduct.UsePositive[N1, AdtCoProduct]]]]]]]]]]]]]]]]]]]]]](AdtFunctionSupportSelf.inputHList21[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12,N13,N14,N15,N16,N17,N18,N19,N20,N21])
      }
    

    }
  